version: "3"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.4.0
    volumes:
      - ./filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/conf/nginx.yml:/usr/share/filebeat/modules.d/nginx.yml
      - ./nginx/log/:/var/log/nginx
      - ./springboot/log/:/var/log/springboot
